### ISSUE TITLE
error when running Find_room.py 

### ISSUE THREAD

**Issue by sivakrkumar** [GuillaumeMorini/roomfinder#6]
Hi
 I am using python 2.7. when I tried to execute find_room.py in my local , it has raised the below error message. Kindly assist.

The syntax of the command is incorrect.
 Traceback (most recent call last):
 File "C:\Users\siramac\Desktop\roomfinder-master\roomfinder-master\find_rooms.
 py", line 57, in 
 rooms.update(findRooms(prefix))
 File "C:\Users\siramac\Desktop\roomfinder-master\roomfinder-master\find_rooms.
 py", line 28, in findRooms
 tree = ET.fromstring(response)
 File "C:\Python27\lib\xml\etree\ElementTree.py", line 1312, in XML
 return parser.close()
 File "C:\Python27\lib\xml\etree\ElementTree.py", line 1665, in close
 self._raiseerror(v)
 File "C:\Python27\lib\xml\etree\ElementTree.py", line 1517, in _raiseerror
 raise err
 xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by GuillaumeMorini** [comment]
Hi,

Either your mail server URL or your password are not good
Your mail server URL should be like this: https://mail.domain.com/ews/exchange.asmx

Kind regards,
